spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: warehouse-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'model'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  file:
    name: logs/warehouse.log
  level:
    root: INFO
